package standard

const (
	// GoJSONOutputArgument asks cmd/go for its machine-readable projection.
	GoJSONOutputArgument = "-json"
	// GoRaceText is the shared Go race-instrumentation identity.
	GoRaceText = "race"
	// GoTestFileSuffix identifies Go's compiler-owned test source convention.
	GoTestFileSuffix = "_test.go"
	// GoTestText identifies cmd/go's test subcommand.
	GoTestText = "test"
)

// Package-owned compiler strings keep Standard's closed enum spellings,
// diagnostics, and report headings in one visible contract. They are not wire
// vocabulary for unrelated Primitive packages.
const (
	admittedTargetInvalidDiagnostic             = "standard admitted target is invalid"
	assuranceAuthorityInvalidDiagnostic         = "standard assurance authority is invalid"
	assuranceStageInvalidDiagnostic             = "standard assurance stage is invalid"
	cachePostureInvalidDiagnostic               = "standard cache posture is invalid"
	capabilityDeclaredAdapterText               = "declared_adapter"
	canonicalCancelledText                      = "cancelled"
	canonicalExperimentText                     = "experiment"
	canonicalPrimitiveText                      = "primitive"
	canonicalProductText                        = "product"
	canonicalProjectText                        = "project"
	canonicalSelectionText                      = "selection"
	canonicalSourceText                         = "source"
	canonicalTimedOutText                       = "timed_out"
	canonicalToolText                           = "tool"
	canonicalUnresolvedText                     = "unresolved"
	complexityAssessmentInvalidDiagnostic       = "standard complexity assessment is invalid"
	complexityCaseInvalidDiagnostic             = "standard complexity case is invalid"
	complexityGrowthInvalidDiagnostic           = "standard complexity growth is invalid"
	componentKindInvalidDiagnostic              = "standard component kind is invalid"
	deliveryStateInvalidDiagnostic              = "standard delivery state is invalid"
	dispositionKindInvalidDiagnostic            = "standard disposition kind is invalid"
	externalSuiteText                           = "external_suite"
	functionReferencePostureInvalidDiagnostic   = "standard function reference posture is invalid"
	infrastructureStageInvalidDiagnostic        = "standard infrastructure stage is invalid"
	machineChangeFieldInvalidDiagnostic         = "standard machine change field is invalid"
	machineInstallModeInvalidDiagnostic         = "standard machine install mode is invalid"
	machineMaintenancePolicyInvalidDiagnostic   = "standard machine maintenance policy is invalid"
	machineProvisioningModelInvalidDiagnostic   = "standard machine provisioning model is invalid"
	machineToolchainKindInvalidDiagnostic       = "standard machine toolchain kind is invalid"
	observationKindInvalidDiagnostic            = "standard observation kind is invalid"
	observationPayloadDisagreementDiagnostic    = "standard observation payload, kind, and probe role disagree"
	outcomeInvalidDiagnostic                    = "standard outcome is invalid"
	primitiveEffectPostureInvalidDiagnostic     = "standard Primitive effect posture is invalid"
	primitiveImplementationText                 = "primitive_implementation"
	probeKindInvalidDiagnostic                  = "standard probe kind is invalid"
	probeRoleInvalidDiagnostic                  = "standard probe role is invalid"
	probeTargetEscapedDiagnostic                = "standard probe target escaped its domain"
	probeTargetKindInvalidDiagnostic            = "standard probe target kind is invalid"
	refusalReasonInvalidDiagnostic              = "standard refusal reason is invalid"
	reportAudienceLabel                         = "Audience"
	reportBenchmarksLabel                       = "Benchmarks"
	reportDeclarationsLabel                     = "Declarations"
	reportFailedLabel                           = "Failed"
	reportNoReferenceObservedLabel              = "No reference observed"
	reportNotAvailableText                      = "not available"
	reportUnavailableText                       = "unavailable"
	reportNonAcceptingLabel                     = "Non-accepting"
	reportObservationsLabel                     = "Observations"
	reportOwnsLabel                             = "Owns"
	reportPassedLabel                           = "Passed"
	reportPlacementInvalidDiagnostic            = "standard report placement is invalid"
	reportProblemLabel                          = "Problem"
	reportProductionReferencedLabel             = "Production referenced"
	reportPurposeLabel                          = "Purpose"
	reportRequestsLabel                         = "Requests"
	reportRevisionLabel                         = "Revision"
	reportRuntimeEntryPointsLabel               = "Runtime entry points"
	reportSurfacesLabel                         = "Surfaces"
	reportTestOnlyLabel                         = "Test only"
	reportUnresolvedLabel                       = "Unresolved"
	sourceAnalysisCompletenessInvalidDiagnostic = "standard source analysis completeness is invalid"
	sourceDeclarationConstantText               = "constant"
	sourceDeclarationKindInvalidDiagnostic      = "standard source declaration kind is invalid"
	sourceFileKindInvalidDiagnostic             = "standard source file kind is invalid"
	sourceImportKindInvalidDiagnostic           = "standard source import kind is invalid"
	sourceLanguageInvalidDiagnostic             = "standard source language is invalid"
	terminalStateInvalidDiagnostic              = "standard terminal state is invalid"
)
