package claims

func emitPackageClaimSpecsAThroughG(emit func(packageClaimSpec) bool) bool {
	specs := [...]packageClaimSpec{
		{
			path: "attest", title: "Bounded typed attestation",
			problem:  "Independent parties need signatures over exact typed facts without each protocol reimplementing framing and canonical hashing.",
			solution: "Attest signs and verifies bounded canonical facts with Ed25519, domain separation, detached envelopes, and caller-selected trust.",
			benefit:  "Every protocol gets one auditable authentication mechanism while retaining ownership of payload meaning and trust policy.",
			removal:  "Remove Attest when Go provides the complete typed canonical-envelope and domain-separated verification agreement directly.",
			owns:     "Attest owns canonical-body hashing, signature framing, domain separation, and proof-carrying verification.",
			excludes: "It does not own key generation, persistence, payload meaning, trust-anchor choice, time, transport, or authorization policy.",
		},
		{
			path: "awsidentity", title: "AWS identity bearer acquisition",
			problem:  "Consumers need one bounded way to exchange a caller-signed AWS STS request for an opaque identity bearer.",
			solution: "Awsidentity validates the signed capability, performs the regional STS exchange, bounds XML decoding, and returns a redacted bearer.",
			benefit:  "Products avoid copying provider wire mechanics and cannot accidentally expose the acquired token through ordinary formatting.",
			removal:  "Remove Awsidentity when no consumer acquires AWS identity bearers or the provider supplies an equally bounded shared Go agreement.",
			owns:     "Awsidentity owns only the STS exchange shape, bounds, provider response validation, and redacted bearer result.",
			excludes: "It does not discover or sign credentials, cache tokens, verify claims, or grant product authority.",
		},
		{
			path: "capabilities", title: "Compiler-owned effect ownership",
			problem:  "Direct operating-system calls can hide duplicate effect owners and copied architectural conventions across packages.",
			solution: "Capabilities exposes the closed Primitive effect taxonomy, exact owner for each effect, and standard-library symbol classifications.",
			benefit:  "Offline inspection can distinguish an owning implementation from a bypass using one compiler-visible source of truth.",
			removal:  "Remove Capabilities when the Go compiler can natively express and enforce package ownership of real-world effects.",
			owns:     "Capabilities owns Primitive effect identities, package ownership, and low-level symbol classification.",
			excludes: "It does not inspect repositories, perform effects, explain why product code exists, or decide product policy.",
		},
		{
			path: "chit", title: "Immutable custody catalogs",
			problem:  "Accepted object receipts need bounded immutable grouping so exact retained objects can be listed and retrieved without interpreting them.",
			solution: "Chit provides signed custody tickets, versioned collections, streaming manifest closure, and bounded catalog pages.",
			benefit:  "Consumers can navigate authenticated custody history without duplicating object truth or loading an unbounded catalog.",
			removal:  "Remove Chit when consumers no longer need signed versioned catalogs above accepted object receipts.",
			owns:     "Chit owns immutable custody-ticket identity, signed collection manifests, versions, and bounded page mechanics.",
			excludes: "It does not decide object eligibility, interpret evidence, transfer objects, or own display policy.",
		},
		{
			path: "chitauth", title: "Authenticated chit queries",
			problem:  "A catalog query must prove that its signing device is the device nominated by an authority-issued installation certificate.",
			solution: "Chitauth binds one device-signed Chit query to its exact installation credential, account, and trusted key.",
			benefit:  "Catalog authentication cannot drift into copied certificate or signature checks at each caller.",
			removal:  "Remove Chitauth when Chit catalog queries no longer cross an independently authenticated installation boundary.",
			owns:     "Chitauth owns the mechanical credential-to-query authentication binding.",
			excludes: "It does not own custody, catalog persistence, account permission, or listing policy.",
		},
		{
			path: "contextstate", title: "Context terminal-state observation",
			problem:  "Packages repeatedly reinterpret cancellation and deadline state or add goroutines around a fact Context already owns.",
			solution: "Contextstate observes Context.Err through one typed bounded contract without clocks, stored contexts, or helper goroutines.",
			benefit:  "Cancellation identity stays exact and callers do not leak work while trying to inspect it.",
			removal:  "Remove Contextstate when no shared boundary needs its typed terminal-state projection beyond context.Err itself.",
			owns:     "Contextstate owns only immediate typed observation of a context terminal state.",
			excludes: "It does not own cancellation causes, timeout aggregation, detachment, process termination, or pipeline precedence.",
		},
		{
			path: "controlplane", title: "Shared signed control-plane documents",
			problem:  "Independently deployed control planes and installations can drift when each side duplicates registration and check-in documents.",
			solution: "Controlplane gives both sides one bounded canonical signed agreement for registration, check-in, and response binding.",
			benefit:  "A wire change breaks compilation or validation rather than becoming a latent field mismatch in production.",
			removal:  "Remove Controlplane when no independent installation exchanges these signed documents with an authority.",
			owns:     "Controlplane owns document shape, bounds, canonical bytes, authentication, and exact request-response binding.",
			excludes: "It does not own product entitlements, account policy, persistence layout, transport, or user-facing state.",
		},
		{
			path: "controlplanetest", title: "Authentic control-plane test fixtures",
			problem:  "Tests that fake installation credentials prove copied fixture assumptions instead of the real authentication chain.",
			solution: "Controlplanetest issues genuine typed authority and device fixtures through the production Controlplane contracts.",
			benefit:  "Hostile tests can exercise real credential binding without restating construction rules.",
			removal:  "Remove Controlplanetest when no test needs a genuine Controlplane installation chain or another test owner supplies the same proof.",
			owns:     "Controlplanetest owns compiler-classified test-only construction of authentic Controlplane fixtures.",
			excludes: "It does not enter production, weaken verification, or define product account and installation policy.",
		},
		{
			path: "controlwire", title: "Control-channel scalar agreement",
			problem:  "Wire revision, nonce, token, route, and replay values drift when client and authority privately copy their spellings and bounds.",
			solution: "Controlwire owns the canonical bounded scalars and closed protocol support both deployments import.",
			benefit:  "The compiler and strict decoder expose disagreement before an installation silently speaks a different protocol.",
			removal:  "Remove Controlwire when no independently deployed control conversation shares these scalar agreements.",
			owns:     "Controlwire owns byte-exact control-channel scalar types, bounds, revisions, routes, and replay identities.",
			excludes: "It does not own registration meaning, account authority, transport execution, or product policy.",
		},
		{
			path: "core", title: "Shared Primitive contracts",
			problem:  "Cross-package limits, identities, paths, errors, and architectural facts become hidden coupling when copied.",
			solution: "Core owns Primitive-wide nominal values, closed enums, strict JSON helpers, stable errors, limits, and the package catalog.",
			benefit:  "Shared mechanical drift becomes a compile or validation failure with no package importing a peer merely for constants.",
			removal:  "Remove a Core contract when it stops being shared; remove Core only when Primitive has no cross-package mechanical agreement.",
			owns:     "Core owns only genuinely shared low-level contracts and Primitive architecture identities.",
			excludes: "It does not own feature policy, provider-specific mechanics, effect execution, human purpose, or a universal data model.",
		},
		{
			path: "currency", title: "Exact currency arithmetic",
			problem:  "Floating-point and untyped integers cannot safely express currency identity, minor units, checked arithmetic, and canonical decimal form.",
			solution: "Currency provides named codes and exact signed minor-unit values with checked arithmetic, ordering, and bounded projection.",
			benefit:  "Mechanical money calculations remain exact while products retain ownership of all commercial meaning.",
			removal:  "Remove Currency when no shared contract needs exact currency-tagged minor-unit arithmetic.",
			owns:     "Currency owns value shape, currency binding, arithmetic overflow checks, and canonical decimal and JSON mechanics.",
			excludes: "It does not own prices, tax, fees, quantities, positivity, provider formats, persistence, or display policy.",
		},
		{
			path: "deploy", title: "Create-only release publication",
			problem:  "Uploading release artifacts without binding manifest identity and provider completion can overwrite truth or claim an attempted deployment as complete.",
			solution: "Deploy publishes an authenticated Release manifest through exact create-only GCS capabilities and returns confirmed receipts.",
			benefit:  "A caller can prove which immutable release bytes reached provider custody without Primitive learning why they matter.",
			removal:  "Remove Deploy when no consumer publishes Release artifacts to GCS or publication moves to another single typed provider owner.",
			owns:     "Deploy owns the orchestration from authenticated release facts to create-only upload capability and confirmed provider result.",
			excludes: "It does not issue capabilities, choose names, retry ambiguous writes, advance Latest, or mutate product state.",
		},
		{
			path: "distribution", title: "Software distribution agreement",
			problem:  "Publishers and installed tools need one exact signed contract for publication, Latest discovery, artifact selection, and upgrade intent.",
			solution: "Distribution defines product-neutral signed release, update, download, and upgrade agreements shared by both sides.",
			benefit:  "CLI products reuse one compiler-owned distribution protocol without copying product or provider policy.",
			removal:  "Remove Distribution when independently shipped tools no longer exchange software publication and update agreements.",
			owns:     "Distribution owns the typed signed agreement linking release identity, selection, artifact, and installed build facts.",
			excludes: "It does not own transfer, installation, provider policy, persistence, scheduling, retries, or customer decisions.",
		},
		{
			path: "distributionauth", title: "Authenticated distribution exchanges",
			problem:  "Publication and upgrade requests must bind to the exact installed device without confusing installation trust with release-manifest trust.",
			solution: "Distributionauth authenticates distribution requests and completions against the authority-issued installation certificate.",
			benefit:  "Installed-tool identity remains compiler-visible and independent from the authority that signs release content.",
			removal:  "Remove Distributionauth when distribution exchanges no longer require installation-bound authentication.",
			owns:     "Distributionauth owns the mechanical installation-credential binding for publication, update, and upgrade exchanges.",
			excludes: "It does not choose releases, admit publication, install software, or define account and entitlement policy.",
		},
		{
			path: "exchange", title: "Typed bounded HTTP mechanics",
			problem:  "Raw net/http leaves each caller to reinvent bounds, retries, replay safety, redirects, streaming custody, and exact request validation.",
			solution: "Exchange adds typed operation policy and bounded O(1)-memory client and server mechanics while preserving net/http semantics.",
			benefit:  "Providers and products share one safe transport wall without sharing payload meaning or growing an alternate runtime.",
			removal:  "Remove an Exchange abstraction when net/http alone supplies its full ownership, validation, bounds, and proof; remove the package when no shared gap remains.",
			owns:     "Exchange owns HTTP request and response mechanics, budgets, retries, replay permission, redirect confinement, bounded documents, streams, and listener custody.",
			excludes: "It does not own payload meaning, object identity, provider authentication policy, persistence, or product authorization.",
		},
		{
			path: "filelock", title: "Cross-process advisory locking",
			problem:  "Go lacks one cross-platform advisory lock contract and private syscall copies misclassify contention, interruption, and failure.",
			solution: "Filelock owns one advisory lock on one already-open file with typed outcomes and caller-owned patience.",
			benefit:  "Processes coordinate through the actual descriptor without copied platform code or PID-file mythology.",
			removal:  "Remove Filelock when Go exposes an equally precise cross-platform advisory lock on open files.",
			owns:     "Filelock owns lock acquisition and release mechanics plus typed contention and platform error classification.",
			excludes: "It does not own file contents, work scheduling, stale PID interpretation, distributed locking, or product coordination policy.",
		},
		{
			path: "filestore", title: "Rooted bounded filesystem effects",
			problem:  "Direct filesystem calls scatter path confinement, streaming limits, durability, atomic replacement, and cleanup behavior.",
			solution: "Filestore composes os.Root and os.File into typed rooted, bounded, streaming filesystem operations.",
			benefit:  "Every consumer crosses one auditable filesystem boundary while retaining ordinary Go handles and semantics.",
			removal:  "Remove a Filestore operation when the standard library supplies the complete validated and receipted effect directly.",
			owns:     "Filestore owns finite filesystem namespace and byte effects, confinement, durability mechanics, and exact observations.",
			excludes: "It does not own filenames, schemas, retention, capacity policy, cloud custody, accounting, or workflows.",
		},
		{
			path: "fuzzfinder", title: "Bounded fuzz artifact discovery",
			problem:  "Go fuzz cache entries and promoted crashers need bounded discovery without guessing their class from indistinguishable generated names.",
			solution: "Fuzzfinder walks one rooted directory with caller-declared classification, bounded memory, and explicit partial accounting.",
			benefit:  "Evidence tools can find exact fuzz artifacts without running fuzzing or building an in-memory filesystem model.",
			removal:  "Remove Fuzzfinder when cmd/go exposes a complete bounded typed artifact inventory.",
			owns:     "Fuzzfinder owns rooted discovery, artifact coordinates, caller-carried class, and partial scan accounting.",
			excludes: "It does not run fuzz targets, mutate files, retain payload custody, or define evidence acceptance.",
		},
		{
			path: "gcsobjects", title: "Authenticated GCS object lifecycle",
			problem:  "Official Cloud Storage SDK mechanics can leak into consumers and diverge from shared exact-object integrity rules.",
			solution: "Gcsobjects isolates SDK clients, bucket and object operations, logical namespaces, generation conditions, and short-lived raw-object capabilities.",
			benefit:  "Consumers receive typed object results while provider terminology stays isolated and transfer integrity stays shared with Objectstore.",
			removal:  "Remove Gcsobjects when no consumer uses GCS or another isolated provider owner replaces the entire lifecycle.",
			owns:     "Gcsobjects owns authenticated GCS SDK construction and provider-specific bucket, object, generation, and capability mechanics.",
			excludes: "It does not own product object meaning, retention policy, customer authorization, or generic multi-provider storage.",
		},
		{
			path: "github", title: "Isolated GitHub source socket",
			problem:  "GitHub App authentication, repository routes, pagination, response limits, and source observations become inconsistent when products implement them independently.",
			solution: "GitHub owns exact GitHub credentials, authenticated bounded exchange, tag and head observations, bounded file reads, and streaming recursive trees.",
			benefit:  "Products consume the same compiler-visible provider facts while retaining all policy about releases, packages, code meaning, and user experience.",
			removal:  "Remove GitHub when no product integrates GitHub or the provider boundary is wholly replaced.",
			owns:     "GitHub owns GitHub-specific authentication, headers, routes, pagination, provider limits, strict projection, streaming, and typed observations.",
			excludes: "It does not select releases, classify packages or files, allow repositories, build source stories, persist UI caches, or decide what completion means.",
		},
		{
			path: "gitrepo", title: "Streaming local Git observation",
			problem:  "Offline tools otherwise copy Git arguments, inherit ambient ignore configuration, or load a repository-wide path model before they can apply their own source policy.",
			solution: "Gitrepo resolves Git, fixes its mechanical environment, and streams validated tracked and repository-unignored paths with exact accounting.",
			benefit:  "Tools receive one bounded typed local-repository observation while retaining every decision about admission, classification, ordering, and meaning.",
			removal:  "Remove Gitrepo when Go or Git exposes the same typed streaming worktree observation directly.",
			owns:     "Gitrepo owns Git command resolution, exact noninteractive environment mechanics, repository-owned ignore execution, streaming path decoding, cancellation, and byte and entry accounting.",
			excludes: "It does not decide which files matter, classify generated content, sort a product projection, inspect code, interpret history, persist findings, or define completion.",
		},
		{
			path: "gomodule", title: "Canonical Go module identities",
			problem:  "Products and tools otherwise copy cmd/go path grammar or treat distinct module and package identities as arbitrary strings.",
			solution: "Gomodule owns validated canonical module paths and package import paths.",
			benefit:  "Go source and tool agreements share one nominal identity without depending on cmd/go internals.",
			removal:  "Remove Gomodule when Go exports an equally stable typed module and import-path contract suitable for shared APIs.",
			owns:     "Gomodule owns lexical Go module and package import identity validation.",
			excludes: "It does not read modules, resolve dependencies, execute cmd/go, or assign product meaning to packages.",
		},
		{
			path: "googleidentity", title: "Google metadata identity acquisition",
			problem:  "Consumers need bounded metadata identity and OAuth bearers without copying proxy, response-authentication, parsing, and redaction rules.",
			solution: "Googleidentity performs confined metadata exchanges and validates bounded token responses into opaque redacted values.",
			benefit:  "Provider credentials cross one hardened socket while authorization and token interpretation stay with receivers.",
			removal:  "Remove Googleidentity when no consumer acquires Google metadata credentials or an equally bounded provider owner replaces it.",
			owns:     "Googleidentity owns Google metadata request shape, no-proxy transport requirements, response validation, bounds, and redacted bearers.",
			excludes: "It does not cache or refresh tokens, verify claims, choose scopes, execute credential tools, or grant authority.",
		},
		{
			path: "gotoolchain", title: "Bounded cmd/go observations",
			problem:  "Callers that shell out to cmd/go copy arguments and parse unbounded output into inconsistent module, package, and build facts.",
			solution: "Gotoolchain executes typed bounded cmd/go requests and converts output into validated Primitive contracts.",
			benefit:  "Go project tools share exact compiler observations without sharing a workflow engine or raw command protocol.",
			removal:  "Remove Gotoolchain when no consumer needs cmd/go observation or Go exposes the same typed in-process contracts.",
			owns:     "Gotoolchain owns cmd/go command resolution, bounded execution plans, decoding, and mechanical result validation.",
			excludes: "It does not decide project policy, acceptance, source purpose, scheduling, or durable run history.",
		},
	}
	for _, spec := range specs {
		if !emit(spec) {
			return false
		}
	}
	return true
}
