package claims

func emitPackageClaimSpecsHThroughR(emit func(packageClaimSpec) bool) bool {
	specs := [...]packageClaimSpec{
		{
			path: "hostfacts", title: "Bounded host observations",
			problem:  "Applications repeatedly probe machine resources through platform-specific files and syscalls that can escape roots, block, or disagree.",
			solution: "Hostfacts reports bounded read-only disk, memory, CPU, terminal, platform, filesystem, and host-path observations.",
			benefit:  "Callers receive exact typed machine facts through one platform-aware owner and decide policy themselves.",
			removal:  "Remove a Hostfacts observation when Go exposes the same bounded fact directly; remove the package when no shared host fact remains.",
			owns:     "Hostfacts owns read-only platform observation and classification of the exact host resource requested.",
			excludes: "It does not mutate limits, supervise processes, monitor continuously, remove files, or choose product action.",
		},
		{
			path: "id", title: "Time-ordered identifiers",
			problem:  "UUIDv7 and ULID identity drifts when packages generate time and entropy internally or depend on incompatible libraries.",
			solution: "Id constructs canonical UUIDv7 and ULID values from caller-supplied temporal and entropy facts.",
			benefit:  "Both sides persist and exchange the same nominal identities while effects remain with their actual owners.",
			removal:  "Remove an Id type when Go provides the same nominal contract and every consumer can adopt it without losing domain separation.",
			owns:     "Id owns pure identifier construction, validation, ordering, and canonical encoding.",
			excludes: "It does not read clocks or entropy, persist identities, assign business meaning, or provide a global generator.",
		},
		{
			path: "keygen", title: "Bounded cryptographic entropy effects",
			problem:  "Direct crypto/rand use scatters bounds, secret ownership, redaction, and key construction across consumers.",
			solution: "Keygen draws exact bounded entropy for Ed25519 keys, generic secret material, and public random tokens.",
			benefit:  "Consumers get validated purpose-neutral material without each becoming an entropy-effect owner.",
			removal:  "Remove Keygen when consumers need no shared bounded entropy operation beyond a standard-library API with the same contract.",
			owns:     "Keygen owns the finite cryptographic random draw and construction of its exact result type.",
			excludes: "It does not derive product keys, choose algorithms dynamically, persist material, rotate secrets, or stream entropy.",
		},
		{
			path: "lease", title: "Signed lease assessment",
			problem:  "Installed software needs a locally verifiable authority decision without importing billing systems or allowing stale signed state to move backward.",
			solution: "Lease validates a fixed-size signed grant, refusal, or revocation and purely assesses it against caller-supplied time and watermarks.",
			benefit:  "Products can apply their own entitlement policy over authenticated monotonic facts without Primitive knowing paid work.",
			removal:  "Remove Lease when no installed product consumes an authority-signed lease decision.",
			owns:     "Lease owns signed decision shape, subject binding, exact timeline, generation monotonicity, and pure assessment.",
			excludes: "It does not own accounts, plans, payments, clocks, persistence, transport, work authorization, or rendering.",
		},
		{
			path: "lineio", title: "Bounded line streaming",
			problem:  "Line-oriented inputs invite whole-file reads or unbounded scanner tokens at every caller.",
			solution: "Lineio turns one io.Reader into a bounded stream using Go scanner semantics.",
			benefit:  "Consumers compose predictable O(1)-memory line processing without copying buffer-limit mechanics.",
			removal:  "Remove Lineio when no shared caller needs its bounded line contract beyond direct bufio use.",
			owns:     "Lineio owns scanner construction, line bounds, iteration, and terminal read error reporting.",
			excludes: "It does not own line meaning, source acquisition, persistence, indexing, or complete-dataset materialization.",
		},
		{
			path: "machineprobe", title: "Admitted machine probe execution",
			problem:  "Machine descriptions can become unsupported assertions unless each fact is tied to the exact bounded probe that observed it.",
			solution: "Machineprobe executes one admitted probe script through Process and returns its validated machine observation.",
			benefit:  "Execution mechanics and captured facts remain reusable while scheduling and acceptance stay independent.",
			removal:  "Remove Machineprobe when machine facts are no longer acquired by an external probe process.",
			owns:     "Machineprobe owns orchestration of one typed admitted probe through the Primitive process boundary.",
			excludes: "It does not schedule fleets, retain history, select machines, accept evidence, or implement Anvil.",
		},
		{
			path: "manual", title: "Typed manual projection",
			problem:  "CLI help, man pages, and machine-readable guidance drift when each output is maintained as independent prose.",
			solution: "Manual validates one product-owned typed book and projects bounded human and machine forms.",
			benefit:  "Every shipped tool can produce consistent guidance from one compiler-owned content structure.",
			removal:  "Remove Manual when consumers no longer need multiple guidance projections from one typed source.",
			owns:     "Manual owns guidance shape, validation, ordering, bounds, and deterministic projection.",
			excludes: "It does not author product commands, decide UX policy, route web pages, or execute the documented operations.",
		},
		{
			path: "objectstore", title: "Exact capability-bound object transfer",
			problem:  "Possession URLs can be spent with wrong bytes, unbounded streams, ambiguous write intent, or no independent integrity result.",
			solution: "Objectstore performs exact bounded upload and download through already-issued HTTPS capabilities with streaming digest proof.",
			benefit:  "Consumers prove transferred extent and content identity without importing a provider SDK or loading objects into memory.",
			removal:  "Remove Objectstore when no consumer spends raw-object capabilities or another single owner supplies identical streaming proof.",
			owns:     "Objectstore owns capability request shape, exact extent, streaming checksums, create-only intent, and commitment classification.",
			excludes: "It does not mint credentials, create buckets, choose object names, retry ambiguity, retain custody, or define provider workflows.",
		},
		{
			path: "payment", title: "Signed payment receipt agreement",
			problem:  "Products need authenticated payment facts without coupling a shared receipt to Stripe, PayPal, or one billing implementation.",
			solution: "Payment defines authority-signed customer receipts and bounded catalogs over exact currency and service periods.",
			benefit:  "Any product can consume one provider-neutral settlement fact while its own policy decides what that purchase permits.",
			removal:  "Remove Payment when no independently deployed product consumes signed payment receipts.",
			owns:     "Payment owns payment-receipt identity, signed shape, exact amount and period binding, and bounded catalog mechanics.",
			excludes: "It does not charge customers, interpret plans, integrate providers, persist billing state, or grant entitlements.",
		},
		{
			path: "paymentauth", title: "Authenticated payment catalog queries",
			problem:  "A payment catalog query must prove that the signing device belongs to the installation and account named by the request.",
			solution: "Paymentauth binds one device-signed query to the authority-issued installation certificate and nominated key.",
			benefit:  "Catalog authentication remains one reusable mechanical seam instead of copied billing-side verification code.",
			removal:  "Remove Paymentauth when payment catalog queries no longer cross an installation-authenticated boundary.",
			owns:     "Paymentauth owns the exact certificate, device-key, account, and query signature binding.",
			excludes: "It does not own billing, receipt issuance, catalog persistence, or account authorization policy.",
		},
		{
			path: "paypal", title: "Isolated PayPal provider socket",
			problem:  "PayPal OAuth, authenticated requests, response limits, and webhook verification use provider-specific rules that should not leak into products or other providers.",
			solution: "Paypal owns the exact PayPal credentials, live and sandbox transport binding, bounded responses, and provider webhook verification exchange.",
			benefit:  "Consumers receive typed provider facts through one hardened socket without accidental coupling to another payment provider.",
			removal:  "Remove Paypal when no product integrates PayPal or the provider boundary is wholly replaced.",
			owns:     "Paypal owns PayPal-specific credential, host, header, OAuth, API, signature, and verification-response mechanics.",
			excludes: "It does not interpret payment meaning, decide refunds or acceptance, store provider state, or share rules with Stripe.",
		},
		{
			path: "plunk", title: "Isolated Plunk provider socket",
			problem:  "Plunk API credentials and webhook bearer verification have provider-specific limits that become unsafe when scattered through email product code.",
			solution: "Plunk owns compatible credentials, authenticated bounded HTTP exchange, and constant-time webhook authentication.",
			benefit:  "Email products consume exact provider results without making their policy layer a transport or secret parser.",
			removal:  "Remove Plunk when no product integrates Plunk or the provider boundary is wholly replaced.",
			owns:     "Plunk owns Plunk-specific credential, authorization-header, request, response, and webhook authentication mechanics.",
			excludes: "It does not interpret email events, select campaigns, store contacts, retry product operations, or grant product authority.",
		},
		{
			path: "process", title: "Typed bounded process execution",
			problem:  "Raw os/exec use scatters cancellation, containment, signal, stream ownership, output bounds, and exit classification.",
			solution: "Process runs one typed command over os/exec with caller-owned streams, independent output bounds, and exact child results.",
			benefit:  "Consumers retain recognizable Go process semantics while crossing one auditable execution boundary.",
			removal:  "Remove a Process feature when os/exec provides its full typed ownership and bound; remove the package when no shared gap remains.",
			owns:     "Process owns command validation, startup, stream forwarding, containment, cancellation delivery, wait, and resource observation.",
			excludes: "It does not parse shells, construct pipelines, schedule work, retain a registry, interpret output, or decide success policy.",
		},
		{
			path: "proofledger", title: "Blind append-only proof chains",
			problem:  "Evidence producers need durable ordering, predecessor linkage, idempotency, and authenticated append results without a ledger learning payload meaning.",
			solution: "Proofledger wraps typed payloads in bounded canonical envelopes and provides expected-head append, immutable hashing, receipts, pages, and streaming verification.",
			benefit:  "Products define their own events while reusing one mechanically verifiable append-only chain.",
			removal:  "Remove Proofledger when no consumer needs a blind authenticated hash chain or another owner supplies the complete agreement.",
			owns:     "Proofledger owns ledger and event identities, envelope encoding, hash linkage, append concurrency, pagination, verification, and append receipts.",
			excludes: "It does not know Work, actors, acceptance, event meaning, product state, storage policy, or what completion means.",
		},
		{
			path: "receipt", title: "Authenticated accepted-evidence receipts",
			problem:  "A successful call or log line does not prove exact evidence entered custody or establish a monotonic accepted coordinate.",
			solution: "Receipt defines authenticated accepted-object facts, sealed result handling, and one fixed-size monotonic watermark.",
			benefit:  "Consumers can advance their own state from durable typed proof without conflating attempts, transport, and acceptance.",
			removal:  "Remove Receipt when no product consumes authenticated accepted-evidence facts or monotonic receipt watermarks.",
			owns:     "Receipt owns accepted-evidence fact shape, authentication binding, zero-on-error results, rejection types, and watermark selection mechanics.",
			excludes: "It does not own transfer, persistence, retries, provider behavior, payment policy, scheduling, or rendering.",
		},
		{
			path: "release", title: "Deterministic release construction",
			problem:  "Release claims drift unless source cleanliness, exact commit, toolchain, target, binary identity, provenance, and Latest selection are bound together.",
			solution: "Release verifies inputs, constructs deterministic build plans, inspects executables, seals manifests, authenticates Latest, and compares installed state.",
			benefit:  "CLI tools share one exact release agreement while external packages retain execution, transfer, installation, and policy.",
			removal:  "Remove Release when no consumer builds or evaluates signed native release artifacts through this agreement.",
			owns:     "Release owns build-input validation, deterministic plan shape, executable inspection, manifest identity, provenance, and Latest decision mechanics.",
			excludes: "It does not create files, execute builds, transfer artifacts, install software, schedule releases, persist state, or retry.",
		},
		{
			path: "retrieval", title: "Exact authenticated object retrieval grants",
			problem:  "A download capability must be bound to the requesting device, exact custody entry, expected object integrity, and short lifetime.",
			solution: "Retrieval defines device-signed requests and authority-signed receive-only grants for exact Chit manifest objects.",
			benefit:  "Products can authorize narrow downloads without exposing provider credentials or interpreting bytes inside Primitive.",
			removal:  "Remove Retrieval when no independently installed tool requests custody-bound object downloads.",
			owns:     "Retrieval owns request and grant shape, signature binding, manifest-entry identity, capability binding, integrity, and lifetime.",
			excludes: "It does not own object contents, storage policy, plans, transport execution, installation, or product authorization decisions.",
		},
		{
			path: "retrievalauth", title: "Authenticated retrieval requests",
			problem:  "A signed retrieval request is not trustworthy until its device key is tied to an authority-issued installation credential.",
			solution: "Retrievalauth verifies the installation certificate and authenticates the request only with the nominated device key.",
			benefit:  "Download authorization receives one compiler-visible identity chain rather than trusting caller-supplied key material.",
			removal:  "Remove Retrievalauth when retrieval no longer crosses an installation-authenticated boundary.",
			owns:     "Retrievalauth owns installation-certificate and device-signature verification for a retrieval request.",
			excludes: "It does not own storage, grant issuance, account plans, download execution, or product access policy.",
		},
		{
			path: "runnercontrol", title: "Domain-blind runner control socket",
			problem:  "An independent requester and runner need exact admission, scheduling, heartbeat, completion, and evidence messages without embedding either product's workflow.",
			solution: "Runnercontrol defines and exchanges typed control messages over the shared Runprotocol agreement.",
			benefit:  "Anvil, Witness, or another authority can coordinate execution without Primitive storing history or deciding acceptance.",
			removal:  "Remove Runnercontrol when no independently deployed runner exchanges this control protocol.",
			owns:     "Runnercontrol owns the mechanical outbound control socket, authentication bindings, delivery states, and message validation.",
			excludes: "It does not own source purpose, test semantics, runner implementation, Firestore history, human review, or completion policy.",
		},
		{
			path: "runprotocol", title: "Independent run fact agreement",
			problem:  "Requesters and execution authorities can falsify or lose accounting when they exchange loose commands, selected output, or duplicated run DTOs.",
			solution: "Runprotocol defines shared typed requests, admission, machine identity, attempts, measurements, artifacts, observations, terminal states, and authorities.",
			benefit:  "Simple local tools and independent runners use the same exact evidence shape without requiring Anvil or a database.",
			removal:  "Remove Runprotocol when no independent boundary exchanges execution facts or another owner supplies the entire typed agreement.",
			owns:     "Runprotocol owns bounded run fact shape, validation, identity derivation, accounting closure, and authority separation.",
			excludes: "It does not inspect source, run commands, retain history, explain code, assess scaling, or decide evidence acceptance.",
		},
		{
			path: "runworkspace", title: "Owned per-run filesystem workspace",
			problem:  "Execution evidence is corrupted when runs share paths, archive hostile names, capture unbounded output, or leave undeclared residue.",
			solution: "Runworkspace creates one confined workspace, acquires source, discovers Go units, captures bounded artifacts, and reports residue through Primitive effects.",
			benefit:  "Runners get deterministic per-run custody without duplicating filesystem and process mechanics.",
			removal:  "Remove Runworkspace when independent execution no longer needs a local owned workspace or another owner replaces the complete lifecycle.",
			owns:     "Runworkspace owns workspace allocation, confinement, source archive handling, discovery, capture paths, artifact finalization, and residue observation.",
			excludes: "It does not schedule runs, interpret tests, accept evidence, retain remote history, or define product completion.",
		},
	}
	for _, spec := range specs {
		if !emit(spec) {
			return false
		}
	}
	return true
}
