package runnercontrol

// Package-owned compiler strings bind Runner Control's closed agreement
// spellings and exact cmd/go observation tokens without leaking product policy.
const (
	authenticationControlRoleText          = "control"
	authenticationGoogleCloudText          = "google_cloud"
	authenticationMutualTLSText            = "mutual_tls"
	authenticationOriginRoleText           = "origin"
	authenticationRunnerRoleText           = "runner"
	coverageModePrefix                     = "mode: "
	diagnosticArtifactText                 = "diagnostic"
	evidenceNotApplicableText              = "not-applicable"
	goCoverageCompilerNilDiagnostic        = "go coverage compiler receiver is nil"
	goTestFailActionText                   = "fail"
	goTestOutputActionText                 = "output"
	goTestNoRunArgument                    = "-run=^$"
	goTestObservationCompilerNilDiagnostic = "go test observation compiler receiver is nil"
	goTestPassActionText                   = "pass"
	goTestSkipActionText                   = "skip"
	heartbeatCancelMemberActionText        = "cancel-member"
	heartbeatCancelUnitActionText          = "cancel-unit"
	heartbeatContinueActionText            = "continue_execution"
	heartbeatDrainActionText               = "drain_execution"
	heartbeatRevokeLeaseActionText         = "revoke-lease"
	isolationDeniedText                    = "denied"
	isolationPinnedText                    = "pinned"
	junitTestCaseElementText               = "testcase"
	machineDrainingStateText               = "draining"
	machineExecutingStateText              = "executing"
	machineReadyStateText                  = "ready"
	networkTCPText                         = "tcp"
	networkUDPText                         = "udp"
	runDeliveredStateText                  = "delivered"
	scheduleRunBatchText                   = "run-batch"
	scheduleRunPlanText                    = "run-plan"
	sequenceWidthFormat                    = "%05d"
	sourceModuleScopeText                  = "module"
	sourceWorkspaceScopeText               = "workspace"
)
